language: ruby
cache: bundler
rvm:
  - 2.4.2
env:
  - DIALECT=context  PIPELINE=$DIALECT
  - DIALECT=latex    PIPELINE=$DIALECT
  - DIALECT=luatex   PIPELINE=$DIALECT
  - DIALECT=pdflatex PIPELINE=$DIALECT
  - DIALECT=pdftex   PIPELINE=$DIALECT
  - DIALECT=tex      PIPELINE=$DIALECT
  - DIALECT=xelatex  PIPELINE=$DIALECT
  - DIALECT=xelatex  PIPELINE=lualatex
  - DIALECT=xetex    PIPELINE=$DIALECT
install:
  # texlive.packages: oberdiek -> atbegshi, ms -> everyshi, graphics -> graphicx
  - source travis/texlive/install
  - bundle install
script: 
  - bundle exec rake install
  - parallel_cucumber --serialize-stdout -- features
branches:
  only:
  - master
