language: ruby
rvm:
- 2.2.5
install:
  # texlive.packages: oberdiek -> atbegshi, ms -> everyshi, graphics -> graphicx
  - source travis/texlive/install
  - bundle install
script: 
  - bundle exec rake install
  - bundle exec rake "features[.*,tex]"
  - bundle exec rake "features[.*,latex]"
branches:
  only:
  - master
