# oberdiek -> atbegshi
# ms -> everyshi
# graphics -> graphicx
language: ruby
rvm:
- 2.2.5
install:
  - source travis/texlive/install
  - bundle install
script: 
  - bundle exec rake install
  - bundle exec rake "features[.*,tex]"
  - bundle exec rake "features[.*,latex]"
  - bundle exec rake "features[.*,context]"
branches:
  only:
  - master
# sudo: false
