language: ruby
cache: bundler
rvm:
  - 2.4.2
env:
  global:
    # We should have ~2 cores on a vm
    - MULTIPLY_PROCESSES=2
    - N=1
    - ONLY_GROUP=1,2
  matrix:
    # ConTeXt run is split because of long runtime
    - FLAVOUR=context N=2 ONLY_GROUP=1,2
    - FLAVOUR=context N=2 ONLY_GROUP=3,4
    - FLAVOUR=latex
    - FLAVOUR=xelatex
    - FLAVOUR=pdflatex
    - FLAVOUR=lualatex
    - FLAVOUR=tex
    - FLAVOUR=xetex
    - FLAVOUR=pdftex
    - FLAVOUR=luatex
install:
  # texlive.packages: oberdiek -> atbegshi, ms -> everyshi, graphics -> graphicx
  - source travis/texlive/install
  - bundle install
script: 
  - bundle exec rake install
  - parallel_cucumber --serialize-stdout --multiply-processes $MULTIPLY_PROCESSES -n $N --only-group $ONLY_GROUP -- features
branches:
  only:
  - master
