language: ruby
rvm:
- 2.2.5
before_script:
  - ./script/tl
  - export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
  - tlmgr install standalone pgf xcolor
  - tlmgr install oberdiek # atbegshi
  - tlmgr install ms # everyshi
  - tlmgr install graphics # graphicx
  - tlmgr install latex-bin
  - tlmgr install context
  - bundle install
script: 
  - bundle exec rake install
  - bundle exec rake features[generic,tex]
  - bundle exec rake features[generic,latex]
  - bundle exec rake features[generic,context]
branches:
  only:
  - master
# sudo: false
