language: ruby
rvm:
- 2.1.2
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install texlive
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install texlive-pictures
  - sudo apt-get install context
  - bundle install
script: 
  - bundle exec rake install
  - bundle exec rake features
branches:
  only:
  - master
# sudo: false
