language: ruby
cache: bundler
rvm:
  - 2.4.2
env:
  global:
    # We should have ~2 cores on a vm
    - MULTIPLY_PROCESSES=2
    - N=1
    - ONLY_GROUP=1,2
  matrix:
    - DIALECT=latex    PIPELINE=$DIALECT
    - DIALECT=luatex   PIPELINE=$DIALECT
    - DIALECT=pdflatex PIPELINE=$DIALECT
    - DIALECT=pdftex   PIPELINE=$DIALECT
    - DIALECT=tex      PIPELINE=$DIALECT
    - DIALECT=xelatex  PIPELINE=$DIALECT
    - DIALECT=xelatex  PIPELINE=lualatex
    - DIALECT=xetex    PIPELINE=$DIALECT
    # ConTeXt run is split because of long runtime
    - DIALECT=context  PIPELINE=$DIALECT N=3 ONLY_GROUP=1,2
    - DIALECT=context  PIPELINE=$DIALECT N=3 ONLY_GROUP=3,4
    - DIALECT=context  PIPELINE=$DIALECT N=3 ONLY_GROUP=5,6
install:
  # texlive.packages: oberdiek -> atbegshi, ms -> everyshi, graphics -> graphicx
  - source travis/texlive/install
  - bundle install
script: 
  - bundle exec rake install
  - parallel_cucumber --serialize-stdout --multiply-processes $MULTIPLY_PROCESSES -n $N --only-group $ONLY_GROUP -- features
branches:
  only:
  - master
