language: ruby
rvm:
- 2.4.0
install:
  # texlive.packages: oberdiek -> atbegshi, ms -> everyshi, graphics -> graphicx
  - source travis/texlive/install
  - bundle install
script: 
  - bundle exec rake install
  - bundle exec rake features
branches:
  only:
  - master
