name: Pre-release
on:
  push:
    branches:
      - development
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run labeller
        id: labeller
        run: |
          # echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
          # echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
          git fetch --unshallow --tags
          GIT_DESCRIPTOR=$(git describe --tags --always)
          echo Detected descriptor ${GIT_DESCRIPTOR}
          echo "TAG=${GIT_DESCRIPTOR}" >> $GITHUB_OUTPUT
          echo "VERSION=${GIT_DESCRIPTOR#v}" >> $GITHUB_OUTPUT

      - name: Setup TeX Live
        uses: paolobrasolin/setup-texlive-action@main
        with:
          cache-key: texlive-${{ matrix.os }}
          packages-path: ${{ github.workspace }}/.github/texlive.release.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile

      - name: Build
        run: |
          make VERSION=${{ steps.labeller.outputs.version }} dist/commutative-diagrams.zip
          cp dist/commutative-diagrams.zip dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip

      - name: Pre-release on Github
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNRELEASED: "update"
        with:
          args: |
            dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip
