name: Release
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      #==[ Shared ]=============================================================

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run labeller
        id: labeller
        run: |
          git fetch --unshallow --tags
          GIT_DESCRIPTOR=$(git describe --tags --always --exclude latest --exclude unreleased)
          echo Detected descriptor: ${GIT_DESCRIPTOR}
          echo "VERSION=${GIT_DESCRIPTOR#v}" >> $GITHUB_OUTPUT

      - name: Install system dependencies
        run: |
          # ghostscript -> ps2pdf
          sudo apt-get update
          sudo apt-get install -y ghostscript

      - name: Setup TeX Live
        uses: paolobrasolin/setup-texlive-action@main
        with:
          cache-key: texlive-release
          packages-path: ${{ github.workspace }}/.github/texlive.release.packages
          profile-path: ${{ github.workspace }}/.github/texlive.profile

      - name: Build
        run: |
          make VERSION=${{ steps.labeller.outputs.version }} dist/commutative-diagrams.zip
          cp dist/commutative-diagrams.zip dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip

      #==[ Pre-release ]========================================================

      - if: startsWith(github.ref, 'refs/heads/')
        name: "GitHub: update pre-release"
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: "${{ steps.labeller.outputs.version }}"
          UNRELEASED: "update"
          UNRELEASED_TAG: unreleased
          PRE_RELEASE: true
          DRAFT_RELEASE: false
        with:
          args: |
            dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip

      #==[ Release ]============================================================

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        name: "GitHub: delete pre-release"
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNRELEASED: "delete"
          UNRELEASED_TAG: unreleased
        with:
          args: |
            dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip

      - if: ${{ startsWith(github.ref, 'refs/tags/') }}
        name: "GitHub: release"
        uses: docker://antonyurchenko/git-release:v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: "${{ steps.labeller.outputs.version }}"
        with:
          args: |
            dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip

      - if: ${{ startsWith(github.ref, 'refs/tags/') && steps.labeller.outputs.version == '1.0.0' }}
        name: "CTAN: submit first release"
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: upload
          file_path: dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip
          fields: |
            update: "false"
            pkg: commutative-diagrams
            version: ${{ steps.labeller.outputs.version }}
            uploader: Paolo Brasolin
            email: paolo.brasolin@gmail.com 
            author: Paolo Brasolin
            license: mit
            ctanPath: /graphics/pgf/contrib/commutative-diagrams
            topic: diagram-comm
            home: https://paolobrasolin.github.io/commutative-diagrams/
            bugs: https://github.com/paolobrasolin/commutative-diagrams/issues
            repository: https://github.com/paolobrasolin/commutative-diagrams
            summary: >
              CoDi: Commutative Diagrams for TeX
            description: >
              CoDi is a TikZ library. Its aim is making commutative diagrams easy to design, parse and tweak.
            note: >
              Extra relevant topics are: diagram-maths diagram maths pgf-tikz

      - if: ${{ startsWith(github.ref, 'refs/tags/') && steps.labeller.outputs.version != '1.0.0' }}
        name: "CTAN: submit update"
        uses: paolobrasolin/ctan-submit-action@v1
        with:
          action: upload
          file_path: dist/commutative-diagrams-${{ steps.labeller.outputs.version }}.zip
          fields: |
            update: "true"
            pkg: commutative-diagrams
            version: ${{ steps.labeller.outputs.version }}
            uploader: Paolo Brasolin
            email: paolo.brasolin@gmail.com
