name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flavour:
          # - tex 
          - etex
          - xetex
          - pdftex
          - luatex
          - latex
          - xelatex
          - pdflatex
          - lualatex
        include:
          # NOTE: context is about 8x slower, so we split the tests
          # NOTE: runners have 2 cores at the moment of writing, but let's account for up to 8
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=1,9,17,25,33,41,49,57" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=2,10,18,26,34,42,50,58" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=3,11,19,27,35,43,51,59" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=4,12,20,28,36,44,52,60" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=5,13,21,29,37,45,53,61" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=6,14,22,30,38,46,54,62" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=7,15,23,31,39,47,55,63" }
          - { flavour: context, extra_flags: "--multiply-processes=8 --only-group=8,16,24,32,40,48,56,64" }
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup TeX Live
      uses: paolobrasolin/setup-texlive-action@main
      with:
        cache-key: texlive-${{ matrix.os }}
        packages-path: ${{ github.workspace }}/.github/texlive.tests.packages
        profile-path: ${{ github.workspace }}/.github/texlive.profile

    - name: Build and install
      run: |
        make SKIP_DOC=1 install
        mktexlsr

    - name: Make MKIV format
      if: ${{ matrix.flavour == 'context' }}
      run: |
        # NOTE: we make MKIV format to avoid parallel ConTeXt tests doing that 
        # concurrently on "first run" leading to flaky failing tests. That was
        # an expensive bug to track down, yeah.
        mtxrun --generate
        context --make

    - name: Setup Ruby and install testing framework
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
        bundler-cache: true

    - name: Run features
      run: >
        FLAVOUR=${{ matrix.flavour }}
        bundle exec parallel_cucumber
        --serialize-stdout
        ${{ matrix.extra_flags }}
        --cucumber-options '--tags ~@flavours'
        --
        features
